name: Deploy to Server

on:
  push:
    branches:
      - master  # yoki deploy qilmoqchi bo'lgan branch nomi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/startUp/  # Serverdagi ishchi papka
            git pull origin main  # Kodni yangilash
            docker-compose up -d --build  # Agar Docker ishlatayotgan bo'lsangiz
            systemctl restart myapp  # Agar servis sifatida ishlasa, servisini qayta yuklash


